const ROLE_SUPERADMIN = "superadmin";
const ROLE_ADMIN_ESCOLA = "admin_escola";
const ROLE_SOMENTE_LEITURA = "somente_leitura";

const ALL_ROLES = [ROLE_SUPERADMIN, ROLE_ADMIN_ESCOLA, ROLE_SOMENTE_LEITURA];
const ASSIGNABLE_ROLES = [ROLE_SUPERADMIN, ROLE_ADMIN_ESCOLA];
const WRITE_ROLES = [ROLE_SUPERADMIN, ROLE_ADMIN_ESCOLA];
const PERIODS = ["morning", "afternoon", "afternoonFriday"];

const PERMISSION_KEYS = {
  menus: ["dashboard", "config", "schools", "users", "audios", "audit"],
  features: [
    "dashboard_summary_view",
    "dashboard_pending_items_view",
    "dashboard_missing_audio_view",
    "dashboard_recent_audit_view",
    "dashboard_open_alerts",
    "dashboard_schools_without_schedule",
    "dashboard_monitor_alerts",
    "dashboard_operational_history",
    "dashboard_http_metrics_view",
    "dashboard_http_metrics_filters",
    "config_schedule_write",
    "config_approve_changes",
    "config_auto_approve_changes",
    "config_templates",
    "config_backup_export",
    "config_backup_import",
    "config_backup_preview",
    "config_backup_refresh",
    "config_backup_restore",
    "audio_manage",
    "schools_create",
    "schools_edit",
    "schools_disable",
    "schools_copy_public_link",
    "users_create",
    "users_edit",
    "users_disable",
    "users_reset_password",
    "users_simulate_login",
    "audit_view",
    "audit_filters",
  ],
};

const ROLE_PERMISSION_DEFAULTS = {
  [ROLE_SUPERADMIN]: {
    menus: { dashboard: true, config: true, schools: true, users: true, audios: true, audit: true },
    features: {
      dashboard_summary_view: true,
      dashboard_pending_items_view: true,
      dashboard_missing_audio_view: true,
      dashboard_recent_audit_view: true,
      dashboard_open_alerts: true,
      dashboard_schools_without_schedule: true,
      dashboard_monitor_alerts: true,
      dashboard_operational_history: true,
      dashboard_http_metrics_view: true,
      dashboard_http_metrics_filters: true,
      config_schedule_write: true,
      config_approve_changes: true,
      config_auto_approve_changes: true,
      config_templates: true,
      config_backup_export: true,
      config_backup_import: true,
      config_backup_preview: true,
      config_backup_refresh: true,
      config_backup_restore: true,
      audio_manage: true,
      schools_create: true,
      schools_edit: true,
      schools_disable: true,
      schools_copy_public_link: true,
      users_create: true,
      users_edit: true,
      users_disable: true,
      users_reset_password: true,
      users_simulate_login: true,
      audit_view: true,
      audit_filters: true,
    },
  },
  [ROLE_ADMIN_ESCOLA]: {
    menus: { dashboard: true, config: true, schools: false, users: true, audios: true, audit: true },
    features: {
      dashboard_summary_view: true,
      dashboard_pending_items_view: true,
      dashboard_missing_audio_view: true,
      dashboard_recent_audit_view: true,
      dashboard_open_alerts: true,
      dashboard_schools_without_schedule: true,
      dashboard_monitor_alerts: true,
      dashboard_operational_history: false,
      dashboard_http_metrics_view: false,
      dashboard_http_metrics_filters: false,
      config_schedule_write: true,
      config_approve_changes: false,
      config_auto_approve_changes: false,
      config_templates: true,
      config_backup_export: true,
      config_backup_import: true,
      config_backup_preview: true,
      config_backup_refresh: true,
      config_backup_restore: true,
      audio_manage: true,
      schools_create: false,
      schools_edit: false,
      schools_disable: false,
      schools_copy_public_link: false,
      users_create: true,
      users_edit: true,
      users_disable: true,
      users_reset_password: false,
      users_simulate_login: false,
      audit_view: true,
      audit_filters: false,
    },
  },
  [ROLE_SOMENTE_LEITURA]: {
    menus: {
      dashboard: true,
      config: true,
      schools: false,
      users: false,
      audios: false,
      audit: true,
    },
    features: {
      dashboard_summary_view: true,
      dashboard_pending_items_view: true,
      dashboard_missing_audio_view: true,
      dashboard_recent_audit_view: true,
      dashboard_open_alerts: true,
      dashboard_schools_without_schedule: true,
      dashboard_monitor_alerts: true,
      dashboard_operational_history: false,
      dashboard_http_metrics_view: false,
      dashboard_http_metrics_filters: false,
      config_schedule_write: false,
      config_approve_changes: false,
      config_auto_approve_changes: false,
      config_templates: false,
      config_backup_export: true,
      config_backup_import: false,
      config_backup_preview: true,
      config_backup_refresh: true,
      config_backup_restore: false,
      audio_manage: false,
      schools_create: false,
      schools_edit: false,
      schools_disable: false,
      schools_copy_public_link: false,
      users_create: false,
      users_edit: false,
      users_disable: false,
      users_reset_password: false,
      users_simulate_login: false,
      audit_view: true,
      audit_filters: false,
    },
  },
};

module.exports = {
  ROLE_SUPERADMIN,
  ROLE_ADMIN_ESCOLA,
  ROLE_SOMENTE_LEITURA,
  ALL_ROLES,
  ASSIGNABLE_ROLES,
  WRITE_ROLES,
  PERIODS,
  PERMISSION_KEYS,
  ROLE_PERMISSION_DEFAULTS,
};
